$inspection=\App\Models\Inspection::find(2);
if(!$inspection){echo "inspection_found=no".PHP_EOL; return;}
echo "inspection_found=yes".PHP_EOL;
echo "status=".(string)$inspection->status.PHP_EOL;
$bdc=(float)($inspection->bdc_annual??0);
$frlc=(float)($inspection->frlc_annual??0);
$fmc=(float)($inspection->fmc_annual??0);
$trc=(float)($inspection->trc_annual??0);
$derived=$bdc+$frlc+$fmc;
echo "bdc_annual=".$bdc.PHP_EOL;
echo "frlc_annual=".$frlc.PHP_EOL;
echo "fmc_annual=".$fmc.PHP_EOL;
echo "trc_annual=".$trc.PHP_EOL;
echo "derived_sum=".$derived.PHP_EOL;
echo "trc_matches=".(abs($trc-$derived)<0.0001?"yes":"no").PHP_EOL;
$activeId=$inspection->active_quotation_id??null;
$quotationClass="App\\Models\\Quotation";
$allQ=class_exists($quotationClass)?$quotationClass::where("inspection_id",2)->orderBy("id")->get(["id","status"]):collect(\Illuminate\Support\Facades\DB::table("quotations")->where("inspection_id",2)->orderBy("id")->get(["id","status"])->all());
if(!$activeId && $allQ->count()===1){$activeId=$allQ->first()->id;}
echo "active_quotation_id=".(is_null($activeId)?"null":$activeId).PHP_EOL;
$activeStatus=null;
if(!is_null($activeId)){$activeStatus=class_exists($quotationClass)?optional($quotationClass::find($activeId))->status:\Illuminate\Support\Facades\DB::table("quotations")->where("id",$activeId)->value("status");}
echo "active_quotation_status=".(is_null($activeStatus)?"null":$activeStatus).PHP_EOL;
$liveStatuses=["shared","client_reviewing","client_responded"];
foreach($liveStatuses as $s){echo "live_count_".$s."=".$allQ->where("status",$s)->count().PHP_EOL;}
$liveQ=$allQ->whereIn("status",$liveStatuses);
$hasLive=$liveQ->count()>0;
echo "has_live_quotations=".($hasLive?"yes":"no").PHP_EOL;
echo "active_in_live_when_live=".($hasLive?(!is_null($activeId)&&$liveQ->pluck("id")->contains($activeId)?"yes":"no"):"n/a").PHP_EOL;
echo "all_quotations=".($allQ->count()?$allQ->map(function($q){return $q->id.":".$q->status;})->implode(", "):"none").PHP_EOL;
